dev:
  children:
    webservers:
      vars:
        ansible_user: dawidw
      hosts:
        ubuntu-01.dawid.in:
          ansible_host: 192.168.1.120
        ubuntu-02.dawid.in:
          ansible_host: 192.168.1.121
    loadbalancer:
      vars:
        ansible_user: dawidw
      hosts:
         ubuntu-03.dawid.in:
          ansible_host: 192.168.1.122

local:
  children:
    dawid_pc:
      hosts:
        master_ansible:
          ansible_host: localhost
          ansible_connection: local
